version: '3.1'
services:
  db:
    image: postgres:13.5
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080

  test-db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - 5433:5432